/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ClosableDialog: typeof import('./src/components/ClosableDialog.vue')['default']
    CloseButton: typeof import('./src/components/CloseButton.vue')['default']
    ElementTestPage: typeof import('./src/components/ElementTestPage.vue')['default']
    ImageCrossfadeSlider: typeof import('./src/components/ImageCrossfadeSlider.vue')['default']
    Loader: typeof import('./src/components/Loader.vue')['default']
    SplashScreen: typeof import('./src/components/SplashScreen.vue')['default']
    TabbedSheet: typeof import('./src/components/TabbedSheet.vue')['default']
    TabPage: typeof import('./src/components/TabPage.vue')['default']
    UserGuide: typeof import('./src/components/UserGuide.vue')['default']
    VideoWrapper: typeof import('./src/components/VideoWrapper.vue')['default']
    WebglTest: typeof import('@/components/WebGlTest.vue')['default']
    WebGlTest: typeof import('./src/components/WebGlTest.vue')['default']
    WwtLoader: typeof import('@/components/Loader.vue')['default']
  }
}
